### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ERR_ASSERTION')

### ISSUE THREAD

**Issue by gacuto** [mendix/widgets-tools#107]
Hi I'm trying to use the widget-tools to create a simple pluggable widget. Everytime I try to run it (fullfilling all required information) I encounter the error:  TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ERR_ASSERTION')

Can you help me on finding the root cause?

Here the full error:

 npx @mendix/generator-widget TextBox
Running widget generator...
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated npmlog@2.0.4: This package is no longer supported.
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated read-package-json@6.0.4: This package is no longer supported. Please use @npmcli/package-json instead.
npm WARN deprecated npmlog@6.0.2: This package is no longer supported.
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm WARN deprecated gauge@1.2.7: This package is no longer supported.
npm WARN deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm WARN deprecated are-we-there-yet@1.1.7: This package is no longer supported.
npm WARN deprecated gauge@4.0.4: This package is no longer supported.

      __  ____   __            _     _            _
     |  \/  \ \ / /           (_)   | |          | |
     | \  / |\ V /   __      ___  __| | ____  ___| |_
     | |\/| | > <    \ \ /\ / / |/ _  |/ _  |/ _ \ __|
     | |  | |/ . \    \ V  V /| | (_| | (_| |  __/ |_
     |_|  |_/_/ \_\    \_/\_/ |_|\__._|\__. |\___|\__|
                                        __/ |
                                       |___/
     Widget Generator, version: 10.15.0

? What is the name of your widget? TextBox
? Enter a description for your widget My widget description
? Organization name Mendix
? Add a copyright © Mendix Technology BV 2022. All rights reserved.
? Add a license Apache-2.0
? Initial version 1.0.0
? Author John
? Mendix project path ../../
? Which programming language do you want to use for the widget? TypeScript
? Which type of components do you want to use? Function Components
? Which type of widget are you developing? For web and hybrid mobile apps
? Which template do you want to use for the widget? Empty widget (recommended for more experienced developers)
? Add unit tests for the widget ? (recommended for Full Boilerplate) No
? Add End-to-end tests for the widget ? (recommended for Full Boilerplate) No
✖️ An error occured while running @mendix/widget:app#writing
Error @mendix/widget@10.15.0 TextBox

Trying to copy from a source that does not exist: C:\Program Files (x86)\Nodist\bin\node_modules\@mendix\generator-widget\generators\app\templates\packages\package_web.json.ejs
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ERR_ASSERTION')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at process.exit (node:internal/process/per_thread:188:24)
    at onError (C:\Program Files (x86)\Nodist\bin\node_modules\yo\lib\cli.js:117:11)
    at C:\Program Files (x86)\Nodist\bin\node_modules\yo\lib\cli.js:168:54
    at async init (C:\Program Files (x86)\Nodist\bin\node_modules\yo\lib\cli.js:168:5)
    at async pre (C:\Program Files (x86)\Nodist\bin\node_modules\yo\lib\cli.js:83:3)
    at async C:\Program Files (x86)\Nodist\bin\node_modules\yo\lib\cli.js:193:3
node:child_process:965
    throw err;
    ^

Error: Command failed: yo @mendix/widget@10.15.0 TextBox
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Object.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\@mendix\generator-widget\bin.js:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 14064,
  stdout: null,
  stderr: null
}

Node.js v20.10.0

**Comment by weirdwater** [comment]
Hi @gacuto, it seems that it is missing a file that should be present in the package. Can you try clearing your `npx` cache? Calling `npx` with a specific package version may also trigger the package to be redownloaded:

```sh
npx '@mendix/generator-widget@10.15.0' TextBox
```
