### ISSUE TITLE
Pluggable Widget Latest version is not working!

### ISSUE THREAD

**Issue by khazaddoom** [mendix/widgets-tools#30]
When i installed pluggable widget code from yoeman generator today, tt installs the folders and structure well but when building the widget it fails with below error.

Running MX Widgets Tools script build:web...
[!] Error: Cannot find module '../dist/typings-generator'

When i inspected i saw that, the @mendix/pluggable-widget-tools (9.23.0) is searching for ../dist/typings-generator folder in it. however the whole dist folder is missing!

Now i tried adding version 9.18.0 and all works well.

Can you please fix it?

**Comment by jeffersonRibeiro** [comment]
Hi @khazaddoom, thanks for reporting the problem.

A MR with the fix has been opened. We will soon release a new patch to fix this.
https://github.com/mendix/widgets-tools/pull/31

**Comment by jeffersonRibeiro** [comment]
Bug fixed. You can now install the latest pluggable-widgets-tools package to solve the problem.

```
npm i @mendix/pluggable-widgets-tools@latest
```
